global:
  scrape_interval: 10s

scrape_configs:
  - job_name: "beats-service"
    metrics_path: "/actuator/prometheus"
    static_configs:
      - targets: ["beats-service:8080"]

  - job_name: "rabbitmq"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["rabbitmq:15692"]
